input_dataset: omni_v1
data_dir: dataset/data
data_aug: True
grid_dim: 128
resolution: .25
latent_grid_dim: 16
latent_resolution: 2.0
latent_ligand_radius: 4.0
elements: ["C", "O", "N", "S", "F", "Cl", "P", "Br"]
n_channels: 8
_n_points:
  "b200": 15_000
  "a100": 12_000
n_points: ${oc.select:dset._n_points.${gpu_type},12_000}
targeted_sampling_ratio: 2
cubes_around: 10
cdrs_aug: ["L1", "L2", "L3", "H1", "H2"]
cdrs: ["H3"]
dumb: 10.0

_num_workers:
  "b200": 24
  "a100": 12
num_workers: ${oc.select:dset._num_workers.${gpu_type},12}
_batch_size:
  "b200": 32
  "a100": 16
batch_size: ${oc.select:dset._batch_size.${gpu_type},16}
lr_enc: 1e-4
lr_dec: 1e-4
beta2: .99
rebalance: True

ligand_radius: 1.0
receptor_radius: 1.0
same_radius: True
use_single_dataset: null
per_patch_coord: True