defaults:
  - sampling: sampling_medium
  - sampler: diffusion_sampling
  - override hydra/job_logging: custom
  - _self_

dset:
  input_dataset: omni_v1
  batch_size: 128
  cdrs: []
  cdrs_aug: ["L1"]
  rebalance: False
  use_single_dataset: "sabdab"
denoiser:
  cfg_dropout: 0.0
debug: False
wandb: True
seed: 1234
fb_pretrained_path: exps/funcbind/fb_unified
exp_name: "sampling_fb_${now:%Y%m%d}_${now:%H%M%S}_${now:%f}"
dirname: ${fb_pretrained_path}/eval_${sampling.split}_${sampler.dirname_sampler}_${exp_name}
out_dir: res
save_dir: ${dirname}/samples/${out_dir}
reg_weight: 1e-5
gpu_type: "b200"  # Options: b200, a100

# set the running dir
hydra:
  run:
    dir: ${save_dir}
  job:
    config:
      override_dirname:
        kv_sep: ""
        item_sep: "_"
        exclude_keys: ["save_dir", "exp_dir", "fb_pretrained_path", "out_dir"]
